apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}
spec:
  replicas: {{.Values.appReplicas}}
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
    spec:
      containers:
        - name: {{.Values.appName}}
          image: "{{ .Values.imageName}}:{{ .Values.imageVersion}}"
          ports:
            - containerPort: {{.Values.containerPort}}
          volumeMounts:
            - name: {{.Values.volumeName}}
              mountPath: {{.Values.mountPath}}
          env:
            - name: PORT
              value: {{.Values.containerPort | quote}}
          livenessProbe:
            tcpSocket:
              port: {{.Values.containerPort}}
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: {{.Values.containerPort}}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: {{.Values.requestedMemory | quote}}
              cpu: {{.Values.requestedCPU | quote}}
            limits:
              memory: {{.Values.memoryLimit | quote}}
      volumes:
        - name: {{.Values.volumeName}}
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
spec:
  type: {{.Values.serviceType}}
  selector:
    app: {{.Values.appName}}
  ports:
    - protocol: TCP
      port: {{.Values.servicePort}}
      targetPort: {{.Values.containerPort}}
