appName: app-name
appReplicas: 2
imageName: image-name
imageVersion: v0.8.0
containerPort: 6666
containerEnv:
  - name: envName
    value: "envValue"
probeType: "grpc"
requestedMemory: "64Mi"
requestedCPU: "100m"
memoryLimit: "120Mi"
serviceType: ClusterIP
servicePort: servicePort
