appName: redis
appReplicas: 2
imageName: redis
imageVersion: alpine
containerPort: 6379
requestedMemory: "90Mi"
requestedCPU: "50m"
memoryLimit: "120Mi"
serviceType: ClusterIP
servicePort: 6379
mountPath: /data
volumeName: redis-volume
