appName: redis
appReplicas: 2
imageName: redis
imageVersion: alpine
containerPort: 6379
requestedMemory: "40Mi"
requestedCPU: "20m"
memoryLimit: "50Mi"
serviceType: ClusterIP
servicePort: 6379
mountPath: /data
volumeName: redis-volume
