appName: redis
appReplicas: 2
imageName: redis
imageVersion: alpine
containerPort: 6379
requestedMemory: "200Mi"
requestedCPU: "70"
memoryLimit: "300Mi"
serviceType: ClusterIP
servicePort: 6379
mountPath: /data
volumeName: redis-volume
